<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>Nexus Programmer</AssemblyName>
    <Product>Nexus Programmer</Product>
    <Authors>mhqb365.com</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/mhqb365/NexusProgrammer</RepositoryUrl>
    <Version>1.1.3</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="icon.ico" />
    <Resource Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Catalog\CH34x_SPI_NOR.tsv" Link="IntegratedICCatalog.tsv"
      CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Catalog\XGecuT48_SPI_NOR.tsv" Link="T48ICCatalog.tsv"
      CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="T48\**\*.cs" />
    <Compile Remove="XGecuT48SDK\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="XGecuT48SDK\src\T48SDK\T48SDK.csproj" />
  </ItemGroup>

</Project>